spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookstore
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate.format_sql: true
